#!/bin/bash

#DEBHELPER#

# Add support for MediaTek mt7921u adapters
echo "mt7921u" > /etc/modules-load.d/mt7921u.conf

# Add support for MediaTek mt7925u adapters
echo "mt7925u" > /etc/modules-load.d/mt7925u.conf

# Support Comfast CF-953AX USB adapter (mt7921u)
echo "Adding support for Comfast CF-953AX USB adapter"
echo 'SUBSYSTEM=="drivers", DEVPATH=="/bus/usb/drivers/mt7921u", ATTR{new_id}="3574 6211"' > /etc/udev/rules.d/99-cf95x.rules

# Support Netgear Nighthawk AXE3000 USB adapter (mt7921u)
echo "Adding support for Netgear Nighthawk AXE3000 USB adapter"
echo 'SUBSYSTEM=="drivers", DEVPATH=="/bus/usb/drivers/mt7921u", ATTR{new_id}="0846 9060"' > /etc/udev/rules.d/99-axe3000.rules

# Support Netgear Nighthawk A9000 USB adapter (mt7925u)
echo "Adding support for Netgear Nighthawk A9000 USB adapter"
echo 'SUBSYSTEM=="drivers", DEVPATH=="/bus/usb/drivers/mt7925u", ATTR{new_id}="0846 9072"' > /etc/udev/rules.d/99-a9000.rules

# If this is not being executed by pi-gen during image build process, apply changes immediately without requiring a reboot
if [ -f /etc/wlanpi-release ]; then
    echo "Adding mt7921u kernel module"
    modprobe mt7921u -q
    echo "Adding mt7925u kernel module"
    modprobe mt7925u -q
fi

# Add Intel Corp. BE200 Bluetooth device name to lsusb
HWDB_FILE="/usr/lib/udev/hwdb.d/99-usb-vendor-model.hwdb"
if [ ! -f "$HWDB_FILE" ]; then
    touch "$HWDB_FILE"
fi
if ! grep -q "usb:v8087p0036" "$HWDB_FILE"; then
echo "Adding Intel Corp. BE200 Bluetooth device name to lsusb"
cat >"$HWDB_FILE" <<'EOL'
# Intel Corp. BE200 Bluetooth device name added by WLAN Pi team
usb:v8087p0036*
 ID_MODEL_FROM_DATABASE=BE200 Bluetooth
EOL
# Refresh systemd-hwdb to add the new device
systemd-hwdb update
fi

# Update lspci PCI device names
echo "Updating lspci PCI device names"
update-pciids

# Deleting BT RAM CODE fixes issues with MT7921AUN Wi-Fi adapters connected to M4 and M4+
MT_USB_ADAPTER_BT_FIRMWARE="/usr/lib/firmware/mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin"
if [ -f "$MT_USB_ADAPTER_BT_FIRMWARE" ]; then
    echo "Deleting MediaTek USB Wi-Fi adapter Bluetooth firmware file"
    sudo rm -f "$MT_USB_ADAPTER_BT_FIRMWARE"
fi

exit 0
