/lib/firmware/mediatek/WIFI_MT7922_patch_mcu_1_1_hdr.bin /lib/firmware/mediatek
/lib/firmware/mediatek/WIFI_MT7961_patch_mcu_1_2_hdr.bin /lib/firmware/mediatek
/lib/firmware/mediatek/BT_RAM_CODE_MT7922_1_1_hdr.bin /lib/firmware/mediatek
#/lib/firmware/mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin /lib/firmware/mediatek
/lib/firmware/mediatek/WIFI_RAM_CODE_MT7922_1.bin /lib/firmware/mediatek
/lib/firmware/mediatek/WIFI_RAM_CODE_MT7961_1.bin /lib/firmware/mediatek
